name: Dart

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Install dependencies
      - name: Install dependencies
        run: cd teacher && flutter pub get

      # Run tests
      - name: Run tests
        run: cd teacher && flutter test
